{% set name = "pyquickbench" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyquickbench-{{ version }}.tar.gz
  sha256: 369d3eee33ef55b86f58077b43afcf1633eea1dd2f7c2f1fa21fab70a5c05387

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - python-build
    - pip
  run:
    - python >=3.9
    - numpy
    - matplotlib-base
    - tqdm
    - ipywidgets

test:
  imports:
    - pyquickbench
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gabrielfougeron/pyquickbench
  summary: A pure Pyton tool to perform time and accuracy benchmarks
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://gabrielfougeron.github.io/pyquickbench/
  dev_url: https://github.com/gabrielfougeron/pyquickbench

extra:
  recipe-maintainers:
    - gabrielfougeron
